# Regenerate bit-exact pins after an intentional kernel change. This is
# the canonical pin/fixture regeneration workflow; use
# tools/bitexact/bitexact_test.jl for cross-vendor forensic comparison.
#
# Re-renders all 20 LDEM timestamps + the full 1m site DEM with Shirley
# 20m farfield,
# captures all SHAs, writes new PNG fixtures, and prints the SHA tables
# in a form that can be pasted into test/bitexact.jl and
# test/fixtures/bitexact/known_good_1m_full_farfield.jl.
#
# Also writes the regenerated LDEM PNGs to data/outputs/bitexact_post_fixes/
# in parallel with test/fixtures/bitexact/, for easy old-vs-new visual diff
# (`data/outputs/bitexact_pre_fixes/` was saved before this script ran).

using Hyperion
const Hyp = Hyperion
import SHA, FileIO
using Dates
using KernelAbstractions: CPU
using Images: RGB, N0f8

PROJECT_ROOT = dirname(dirname(@__DIR__))
FIXTURES = joinpath(PROJECT_ROOT, "test", "fixtures", "bitexact")
FIXTURES_1M = joinpath(PROJECT_ROOT, "test", "fixtures",
                       "bitexact_1m_full_farfield")
COMPARE_DIR = joinpath(PROJECT_ROOT, "data", "outputs", "bitexact_post_fixes")
mkpath(COMPARE_DIR)
mkpath(FIXTURES_1M)

const BACKEND_NAME = lowercase(get(ENV, "HYP_BACKEND", "metal"))
const STACK_BACKEND, STACK_DEVICE_ARRAY = if BACKEND_NAME == "metal"
    @eval using Metal
    (Metal.MetalBackend(), Metal.MtlArray)
elseif BACKEND_NAME == "cuda"
    @eval using CUDA
    (CUDA.CUDABackend(), CUDA.CuArray)
elseif BACKEND_NAME == "cpu"
    (CPU(), Array)
else
    error("Unknown HYP_BACKEND='$BACKEND_NAME' - use metal|cuda|cpu")
end

# ─── Identical to the helpers in test/bitexact.jl ─────────────────────────
sha256_bytes(v::AbstractArray) = bytes2hex(SHA.sha256(collect(reinterpret(UInt8, vec(v)))))

function _palette_apply(data::Matrix{UInt8}, palette::Matrix{UInt8})
    H, W = size(data)
    rgb = Array{UInt8, 3}(undef, 3, H, W)
    @inbounds for c in 1:W, r in 1:H
        idx = data[r, c] + 1
        rgb[1, r, c] = palette[idx, 1]
        rgb[2, r, c] = palette[idx, 2]
        rgb[3, r, c] = palette[idx, 3]
    end
    return rgb
end

# ─── LDEM regeneration ────────────────────────────────────────────────────
const TIMESTAMPS = [
    "2027-01-05T00-00-00", "2027-01-22T07-00-00", "2027-02-12T12-00-00",
    "2027-02-28T04-00-00", "2027-03-20T06-00-00", "2027-04-08T18-00-00",
    "2027-05-15T00-00-00", "2027-05-24T19-00-00", "2027-06-01T00-00-00",
    "2027-06-21T12-00-00", "2027-06-23T00-00-00", "2027-07-04T03-00-00",
    "2027-07-16T08-00-00", "2027-08-05T11-00-00", "2027-08-20T15-00-00",
    "2027-09-10T00-00-00", "2027-10-05T21-00-00", "2027-10-27T14-00-00",
    "2027-11-11T12-00-00", "2027-12-21T00-00-00",
]

println("Regenerating LDEM bit-exact pins ($(length(TIMESTAMPS)) timestamps) ...")
ldem = Hyp.load_ldem(Hyp.require_shirley_ldem!())
Hyp.init_spice(joinpath(PROJECT_ROOT, "kernels"))
max_mm, min_mm = Hyp.build_ldem_mipmaps_minmax(ldem.data)
const ORIGIN_R, ORIGIN_C = 8960, 18432
const H, W = 512, 896

# Open the SHA table file for writing.
sha_path = joinpath(PROJECT_ROOT, "data", "outputs", "regenerated_pins_LDEM.txt")
open(sha_path, "w") do io
    println(io, "# Generated by tools/fixtures/regenerate_bitexact_pins.jl")
    println(io, "# Paste into test/bitexact.jl KNOWN_GOOD")
    println(io, "const KNOWN_GOOD = Dict{String, NamedTuple}(")
    for ts in TIMESTAMPS
        print("  $ts ... "); flush(stdout)
        t0 = time()
        dt = DateTime(ts, dateformat"yyyy-mm-ddTHH-MM-SS")
        et = Hyp.datetime_to_et(dt)
        sun_t = Tuple(Hyp.get_body_position(Hyp.NAIF_SUN, et))
        earth_t = Tuple(Hyp.get_body_position(Hyp.NAIF_EARTH, et))

        sun, dsn, de, sun_rays = Hyp.generate_live_shadow_frame_gpu(
            ldem.data, ORIGIN_R, ORIGIN_C, H, W, sun_t, earth_t, 0.0;
            max_mipmaps = max_mm, min_mipmaps = min_mm,
            backend = CPU(), DeviceArray = Array)

        # CPU precompute buffer
        sun_rc, sun_rs, sun_el, earth_rc, earth_rs, earth_el, sun_tan, dsn_tan =
            Hyp._precompute_azel(ldem.data, ORIGIN_R, ORIGIN_C, H, W,
                                sun_t, earth_t, Float32(0.0))
        azel_bytes = vcat(vec(sun_rc), vec(sun_rs), vec(sun_el),
                          vec(earth_rc), vec(earth_rs), vec(earth_el),
                          vec(sun_tan), vec(dsn_tan))
        azel_sha = bytes2hex(SHA.sha256(reinterpret(UInt8, azel_bytes)))

        sun_rgb = _palette_apply(sun, Hyp.SUN_PALETTE)
        dsn_rgb = _palette_apply(dsn, Hyp.DSN_PALETTE)

        # Write PNG fixtures (overwrite test/fixtures/bitexact/ + copy to compare dir)
        function _save_indexed(path, data, palette)
            Hyp.save_indexed_png(data, palette, path)
        end
        _save_indexed(joinpath(FIXTURES,    "$(ts)_sun.png"), sun, Hyp.SUN_PALETTE)
        _save_indexed(joinpath(FIXTURES,    "$(ts)_dsn.png"), dsn, Hyp.DSN_PALETTE)
        _save_indexed(joinpath(COMPARE_DIR, "$(ts)_sun.png"), sun, Hyp.SUN_PALETTE)
        _save_indexed(joinpath(COMPARE_DIR, "$(ts)_dsn.png"), dsn, Hyp.DSN_PALETTE)

        # Emit the NamedTuple entry
        println(io, "    \"$ts\" => (")
        println(io, "        sun     = \"$(sha256_bytes(sun))\",")
        println(io, "        dsn     = \"$(sha256_bytes(dsn))\",")
        println(io, "        sun_rgb = \"$(sha256_bytes(sun_rgb))\",")
        println(io, "        dsn_rgb = \"$(sha256_bytes(dsn_rgb))\",")
        println(io, "        de      = \"$(sha256_bytes(de))\",")
        println(io, "        azel    = \"$azel_sha\",")
        for k in 1:8
            println(io, "        d_$(k-1)     = \"$(sha256_bytes(view(sun_rays, :, :, k)))\",")
        end
        println(io, "    ),")
        flush(io)
        println("$(round(time()-t0; digits=0))s")
    end
    println(io, ")")
end

# ─── Full 1m site + 20m farfield regeneration ────────────────────────────
println()
println("Regenerating full 1m site + Shirley 20m farfield pins ($(length(TIMESTAMPS)) timestamps) ...")
println("1m stack backend: $BACKEND_NAME")
site = Hyp.load_site_dem_f32(Hyp.require_nobile_1m_tif!())
far = Hyp.PolarStereoTerrain(ldem.data;
    max_mipmaps = max_mm,
    min_mipmaps = min_mm,
    elev_scale_to_m = ldem.elev_scale_to_m)
stack = Hyp.TerrainStack(
    Hyp.SiteTerrain(site; window = (0, 0, site.H, site.W)),
    far)

site_path = joinpath(PROJECT_ROOT, "test", "fixtures", "bitexact",
                     "known_good_1m_full_farfield.jl")
open(site_path, "w") do io
    println(io, "# Generated by tools/fixtures/regenerate_bitexact_pins.jl")
    println(io, "# backend=$BACKEND_NAME")
    println(io, "const KNOWN_GOOD_1M_FULL_FARFIELD = Dict{String, NamedTuple}(")
    for ts in TIMESTAMPS
        print("  $ts ... "); flush(stdout)
        t0 = time()
        dt = DateTime(ts, dateformat"yyyy-mm-ddTHH-MM-SS")
        et = Hyp.datetime_to_et(dt)
        sun_t = Tuple(Hyp.get_body_position(Hyp.NAIF_SUN, et))
        earth_t = Tuple(Hyp.get_body_position(Hyp.NAIF_EARTH, et))

        sun, dsn, de, sun_rays = Hyp.render_terrain_stack_gpu(
            stack, sun_t, earth_t, 0.0;
            backend = STACK_BACKEND,
            DeviceArray = STACK_DEVICE_ARRAY)
        sun_rgb = _palette_apply(sun, Hyp.SUN_PALETTE)
        dsn_rgb = _palette_apply(dsn, Hyp.DSN_PALETTE)
        Hyp.save_indexed_png(sun, Hyp.SUN_PALETTE,
                             joinpath(FIXTURES_1M, "$(ts)_sun.png"))
        Hyp.save_indexed_png(dsn, Hyp.DSN_PALETTE,
                             joinpath(FIXTURES_1M, "$(ts)_dsn.png"))

        println(io, "    \"$ts\" => (")
        println(io, "        sun     = \"$(sha256_bytes(sun))\",")
        println(io, "        dsn     = \"$(sha256_bytes(dsn))\",")
        println(io, "        sun_rgb = \"$(sha256_bytes(sun_rgb))\",")
        println(io, "        dsn_rgb = \"$(sha256_bytes(dsn_rgb))\",")
        println(io, "        de      = \"$(sha256_bytes(de))\",")
        for k in 1:8
            println(io, "        d_$(k-1)     = \"$(sha256_bytes(view(sun_rays, :, :, k)))\",")
        end
        println(io, "    ),")
        flush(io)
        println("$(round(time()-t0; digits=0))s")
    end
    println(io, ")")
end

println("Wrote new SHA tables:")
println("  $sha_path")
println("  $site_path")
println()
println("PNG fixtures regenerated in test/fixtures/bitexact/")
println("Old (pre-fix) PNGs preserved in data/outputs/bitexact_pre_fixes/")
println("New PNGs also saved to data/outputs/bitexact_post_fixes/ for visual diff")
