using Dates
using Hyperion
const Hyp = Hyperion
using KernelAbstractions: CPU
import SHA

const PROJECT_ROOT = dirname(@__DIR__)
const FIXTURES =
    joinpath(PROJECT_ROOT, "test", "fixtures", "bitexact_1m_viper8_barker2023")
const KNOWN_GOOD_PATH =
    joinpath(PROJECT_ROOT, "test", "fixtures", "bitexact",
             "known_good_1m_viper8_barker2023.jl")

const BACKEND_NAME = lowercase(get(ENV, "HYP_BACKEND", "metal"))
const STACK_BACKEND, STACK_DEVICE_ARRAY = if BACKEND_NAME == "metal"
    @eval using Metal
    (Metal.MetalBackend(), Metal.MtlArray)
elseif BACKEND_NAME == "cuda"
    @eval using CUDA
    (CUDA.CUDABackend(), CUDA.CuArray)
elseif BACKEND_NAME == "cpu"
    (CPU(), Array)
else
    error("Unknown HYP_BACKEND='$BACKEND_NAME' - use metal|cuda|cpu")
end

const TIMESTAMPS = [
    "2027-01-05T00-00-00", "2027-01-22T07-00-00", "2027-02-12T12-00-00",
    "2027-02-28T04-00-00", "2027-03-20T06-00-00", "2027-04-08T18-00-00",
    "2027-05-15T00-00-00", "2027-05-24T19-00-00", "2027-06-01T00-00-00",
    "2027-06-21T12-00-00", "2027-06-23T00-00-00", "2027-07-04T03-00-00",
    "2027-07-16T08-00-00", "2027-08-05T11-00-00", "2027-08-20T15-00-00",
    "2027-09-10T00-00-00", "2027-10-05T21-00-00", "2027-10-27T14-00-00",
    "2027-11-11T12-00-00", "2027-12-21T00-00-00",
]

sha256_bytes(v::AbstractArray) =
    bytes2hex(SHA.sha256(collect(reinterpret(UInt8, vec(v)))))

function _palette_apply(data::Matrix{UInt8}, palette::Matrix{UInt8})
    H, W = size(data)
    rgb = Array{UInt8, 3}(undef, 3, H, W)
    @inbounds for c in 1:W, r in 1:H
        idx = data[r, c] + 1
        rgb[1, r, c] = palette[idx, 1]
        rgb[2, r, c] = palette[idx, 2]
        rgb[3, r, c] = palette[idx, 3]
    end
    return rgb
end

function main()
    mkpath(FIXTURES)
    println("Backend: $BACKEND_NAME")
    println("Site DEM: $(Hyp.require_viper8_nobile_crop_tif!())")
    println("Farfield: $(Hyp.require_barker_2023_ldem!())")

    site = Hyp.load_site_dem_f32(Hyp.require_viper8_nobile_crop_tif!())
    ldem = Hyp.load_ldem(Hyp.require_barker_2023_ldem!())
    println("Building Barker 2023 farfield mipmaps ...")
    ldem_max, ldem_min = Hyp.build_ldem_mipmaps_minmax(ldem.data)
    far = Hyp.PolarStereoTerrain(ldem.data;
        max_mipmaps = ldem_max,
        min_mipmaps = ldem_min,
        elev_scale_to_m = ldem.elev_scale_to_m)
    stack = Hyp.TerrainStack(
        Hyp.SiteTerrain(site; window = (0, 0, site.H, site.W)),
        far)

    Hyp.init_spice(joinpath(PROJECT_ROOT, "kernels"))

    open(KNOWN_GOOD_PATH, "w") do io
        println(io, "# Generated by scripts/generate_viper8_barker2023_bitexact.jl")
        println(io, "# backend=$BACKEND_NAME")
        println(io, "const KNOWN_GOOD_1M_VIPER8_BARKER2023 = Dict{String, NamedTuple}(")
        for ts in TIMESTAMPS
            print("  $ts ... "); flush(stdout)
            t0 = time()
            dt = DateTime(ts, dateformat"yyyy-mm-ddTHH-MM-SS")
            et = Hyp.datetime_to_et(dt)
            sun_t = Tuple(Hyp.get_body_position(Hyp.NAIF_SUN, et))
            earth_t = Tuple(Hyp.get_body_position(Hyp.NAIF_EARTH, et))

            sun, dsn, de, sun_rays = Hyp.render_terrain_stack_gpu(
                stack, sun_t, earth_t, 0.0;
                backend = STACK_BACKEND,
                DeviceArray = STACK_DEVICE_ARRAY)

            sun_rgb = _palette_apply(sun, Hyp.SUN_PALETTE)
            dsn_rgb = _palette_apply(dsn, Hyp.DSN_PALETTE)
            Hyp.save_indexed_png(sun, Hyp.SUN_PALETTE,
                                 joinpath(FIXTURES, "$(ts)_sun.png"))
            Hyp.save_indexed_png(dsn, Hyp.DSN_PALETTE,
                                 joinpath(FIXTURES, "$(ts)_dsn.png"))

            println(io, "    \"$ts\" => (")
            println(io, "        sun     = \"$(sha256_bytes(sun))\",")
            println(io, "        dsn     = \"$(sha256_bytes(dsn))\",")
            println(io, "        sun_rgb = \"$(sha256_bytes(sun_rgb))\",")
            println(io, "        dsn_rgb = \"$(sha256_bytes(dsn_rgb))\",")
            println(io, "        de      = \"$(sha256_bytes(de))\",")
            for k in 1:8
                println(io, "        d_$(k-1)     = \"$(sha256_bytes(view(sun_rays, :, :, k)))\",")
            end
            println(io, "    ),")
            flush(io)
            println("$(round(time() - t0; digits=1))s")
        end
        println(io, ")")
    end
    println("Wrote $KNOWN_GOOD_PATH")
    println("Wrote PNG fixtures in $FIXTURES")
end

main()
