# Regenerate bit-exact pins after the kernel changes since 0f0b691.
#
# Re-renders all 20 LDEM timestamps + the 1m site DEM pinned region,
# captures all SHAs, writes new PNG fixtures, and prints the SHA tables
# in a form that can be pasted into test/bitexact.jl and test/site_1m.jl.
#
# Also writes the regenerated LDEM PNGs to data/outputs/bitexact_post_fixes/
# in parallel with test/fixtures/bitexact/, for easy old-vs-new visual diff
# (`data/outputs/bitexact_pre_fixes/` was saved before this script ran).

using JuliaMapbuilder
const JM = JuliaMapbuilder
import SHA, FileIO
using Dates
using KernelAbstractions: CPU
using Images: RGB, N0f8

PROJECT_ROOT = dirname(@__DIR__)
FIXTURES = joinpath(PROJECT_ROOT, "test", "fixtures", "bitexact")
COMPARE_DIR = joinpath(PROJECT_ROOT, "data", "outputs", "bitexact_post_fixes")
mkpath(COMPARE_DIR)

# ─── Identical to the helpers in test/bitexact.jl ─────────────────────────
sha256_bytes(v::AbstractArray) = bytes2hex(SHA.sha256(collect(reinterpret(UInt8, vec(v)))))

function _palette_apply(data::Matrix{UInt8}, palette::Matrix{UInt8})
    H, W = size(data)
    rgb = Array{UInt8, 3}(undef, 3, H, W)
    @inbounds for c in 1:W, r in 1:H
        idx = data[r, c] + 1
        rgb[1, r, c] = palette[idx, 1]
        rgb[2, r, c] = palette[idx, 2]
        rgb[3, r, c] = palette[idx, 3]
    end
    return rgb
end

# ─── LDEM regeneration ────────────────────────────────────────────────────
const TIMESTAMPS = [
    "2027-01-05T00-00-00", "2027-01-22T07-00-00", "2027-02-12T12-00-00",
    "2027-02-28T04-00-00", "2027-03-20T06-00-00", "2027-04-08T18-00-00",
    "2027-05-15T00-00-00", "2027-05-24T19-00-00", "2027-06-01T00-00-00",
    "2027-06-21T12-00-00", "2027-06-23T00-00-00", "2027-07-04T03-00-00",
    "2027-07-16T08-00-00", "2027-08-05T11-00-00", "2027-08-20T15-00-00",
    "2027-09-10T00-00-00", "2027-10-05T21-00-00", "2027-10-27T14-00-00",
    "2027-11-11T12-00-00", "2027-12-21T00-00-00",
]

println("Regenerating LDEM bit-exact pins ($(length(TIMESTAMPS)) timestamps) ...")
ldem = JM.load_ldem("/Volumes/WD_BLACK/mapbuilder/test_inputs/ldem_80s_20m.img")
JM.init_spice(joinpath(PROJECT_ROOT, "kernels"))
max_mm, min_mm = JM.build_ldem_mipmaps_minmax(ldem.data)
const ORIGIN_R, ORIGIN_C = 8960, 18432
const H, W = 512, 896

# Open the SHA table file for writing.
sha_path = joinpath(PROJECT_ROOT, "scripts", "regenerated_pins_LDEM.txt")
open(sha_path, "w") do io
    println(io, "# Generated by scripts/regenerate_pins.jl")
    println(io, "# Paste into test/bitexact.jl KNOWN_GOOD")
    println(io, "const KNOWN_GOOD = Dict{String, NamedTuple}(")
    for ts in TIMESTAMPS
        print("  $ts ... "); flush(stdout)
        t0 = time()
        dt = DateTime(ts, dateformat"yyyy-mm-ddTHH-MM-SS")
        et = JM.datetime_to_et(dt)
        sun_t = Tuple(JM.get_body_position(JM.NAIF_SUN, et))
        earth_t = Tuple(JM.get_body_position(JM.NAIF_EARTH, et))

        sun, dsn, de, sun_rays = JM.generate_live_shadow_frame_gpu(
            ldem.data, ORIGIN_R, ORIGIN_C, H, W, sun_t, earth_t, 0.0;
            max_mipmaps = max_mm, min_mipmaps = min_mm,
            backend = CPU(), DeviceArray = Array)

        # CPU precompute buffer
        sun_rc, sun_rs, sun_el, earth_rc, earth_rs, earth_el, sun_tan, dsn_tan =
            JM._precompute_azel(ldem.data, ORIGIN_R, ORIGIN_C, H, W,
                                sun_t, earth_t, Float32(0.0))
        azel_bytes = vcat(vec(sun_rc), vec(sun_rs), vec(sun_el),
                          vec(earth_rc), vec(earth_rs), vec(earth_el),
                          vec(sun_tan), vec(dsn_tan))
        azel_sha = bytes2hex(SHA.sha256(reinterpret(UInt8, azel_bytes)))

        sun_rgb = _palette_apply(sun, JM.SUN_PALETTE)
        dsn_rgb = _palette_apply(dsn, JM.DSN_PALETTE)

        # Write PNG fixtures (overwrite test/fixtures/bitexact/ + copy to compare dir)
        function _save_indexed(path, data, palette)
            JM.save_indexed_png(data, palette, path)
        end
        _save_indexed(joinpath(FIXTURES,    "$(ts)_sun.png"), sun, JM.SUN_PALETTE)
        _save_indexed(joinpath(FIXTURES,    "$(ts)_dsn.png"), dsn, JM.DSN_PALETTE)
        _save_indexed(joinpath(COMPARE_DIR, "$(ts)_sun.png"), sun, JM.SUN_PALETTE)
        _save_indexed(joinpath(COMPARE_DIR, "$(ts)_dsn.png"), dsn, JM.DSN_PALETTE)

        # Emit the NamedTuple entry
        println(io, "    \"$ts\" => (")
        println(io, "        sun     = \"$(sha256_bytes(sun))\",")
        println(io, "        dsn     = \"$(sha256_bytes(dsn))\",")
        println(io, "        sun_rgb = \"$(sha256_bytes(sun_rgb))\",")
        println(io, "        dsn_rgb = \"$(sha256_bytes(dsn_rgb))\",")
        println(io, "        de      = \"$(sha256_bytes(de))\",")
        println(io, "        azel    = \"$azel_sha\",")
        for k in 1:8
            println(io, "        d_$(k-1)     = \"$(sha256_bytes(view(sun_rays, :, :, k)))\",")
        end
        println(io, "    ),")
        flush(io)
        println("$(round(time()-t0; digits=0))s")
    end
    println(io, ")")
end

# ─── 1m site DEM regeneration ────────────────────────────────────────────
println()
println("Regenerating 1m site DEM bit-exact pin ...")
site = JM.load_site_dem("/Volumes/WD_BLACK/mapbuilder/test_inputs/nobile_1m.tif")
max_smm, min_smm = JM.build_site_mipmaps_minmax(site)

const SITE_TS = "2027-06-01T00-00-00"
const SITE_OR, SITE_OC = 3500, 3500
const SITE_H, SITE_W = 256, 256

dt = DateTime(SITE_TS, dateformat"yyyy-mm-ddTHH-MM-SS")
et = JM.datetime_to_et(dt)
sun_t = Tuple(JM.get_body_position(JM.NAIF_SUN, et))
earth_t = Tuple(JM.get_body_position(JM.NAIF_EARTH, et))

sun, dsn, de, sun_rays = JM.generate_live_shadow_frame_site_gpu(
    site, sun_t, earth_t, 0.0;
    max_mipmaps = max_smm, min_mipmaps = min_smm,
    backend = CPU(), DeviceArray = Array,
    origin_r = SITE_OR, origin_c = SITE_OC, H = SITE_H, W = SITE_W)

data_sub = site.data[SITE_OR+1:SITE_OR+SITE_H, SITE_OC+1:SITE_OC+SITE_W]

sun_local   = JM._moonme_to_local(sun_t,   site.lat0, site.lon0)
earth_local = JM._moonme_to_local(earth_t, site.lat0, site.lon0)
sun_rc, sun_rs, sun_el, earth_rc, earth_rs, earth_el, sun_tan, dsn_tan =
    JM._precompute_azel(site.data, SITE_OR, SITE_OC, SITE_H, SITE_W,
                        sun_local, earth_local, Float32(0.0);
                        s0 = Float32(site.s0), l0 = Float32(site.l0),
                        pixel_size_km = Float32(site.pixel_size_m / 1000.0))
azel_bytes = vcat(vec(sun_rc), vec(sun_rs), vec(sun_el),
                  vec(earth_rc), vec(earth_rs), vec(earth_el),
                  vec(sun_tan), vec(dsn_tan))

site_path = joinpath(PROJECT_ROOT, "scripts", "regenerated_pins_SITE.txt")
open(site_path, "w") do io
    println(io, "# Generated by scripts/regenerate_pins.jl")
    println(io, "# Paste into test/site_1m.jl SITE_KNOWN_GOOD")
    println(io, "const SITE_KNOWN_GOOD = (")
    println(io, "    site_tif_path = SITE_TIF_PATH,")
    println(io, "    timestamp     = \"$SITE_TS\",")
    println(io, "    origin_r = $SITE_OR, origin_c = $SITE_OC, H = $SITE_H, W = $SITE_W,")
    println(io)
    println(io, "    data_sub = \"$(sha256_bytes(data_sub))\",")
    println(io, "    azel     = \"$(bytes2hex(SHA.sha256(reinterpret(UInt8, azel_bytes))))\",")
    println(io, "    sun      = \"$(sha256_bytes(sun))\",")
    println(io, "    dsn      = \"$(sha256_bytes(dsn))\",")
    println(io, "    de       = \"$(sha256_bytes(de))\",")
    for k in 1:8
        println(io, "    d_$(k-1)      = \"$(sha256_bytes(view(sun_rays, :, :, k)))\",")
    end
    println(io, ")")
end

println("Wrote new SHA tables:")
println("  $sha_path")
println("  $site_path")
println()
println("PNG fixtures regenerated in test/fixtures/bitexact/")
println("Old (pre-fix) PNGs preserved in data/outputs/bitexact_pre_fixes/")
println("New PNGs also saved to data/outputs/bitexact_post_fixes/ for visual diff")
